version: "3.6"

services:

  rabbitMQ:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - data:/var/lib/rabbitmq

  gateway:
    build: ./apigateway
    ports:
      - "8080:8080"
    depends_on:
      - user
      - product
      - order

  user:
    build: ./microservice-users
    ports:
      - "8082:8082"
    depends_on:
      - db

  product:
    build: ./microcervice-products
    ports:
      - "8083:8083"
    depends_on:
      - db

  order:
    build: ./microservice-order
    ports:
      - "8081:8081"
    depends_on:
      - db


  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/casa/volumes-db/mysql-data:/var/lib/mysql:rw



volumes:
  mysql-data:
  data:
