version: "3.6"

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user123

  gateway:
    build: ../cloud/apigateway
    ports:
      - "8080:8080"
    depends_on:
      - user
      - product
      - order

  registry-server:
    build: ../cloud/registry-server
    ports:
      - "8761:8761"

  config-server:
    build: ../cloud/config-server
    ports:
      - "8088:8088"

  user:
    build: ../microservice/user-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - registry-server
      - db

  product:
    build: ../microservice/product-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - registry-server
      - db

  order:
    build: ../microservice/order-service
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - registry-server
      - db


  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/casa/volumes-db/mysql-data:/var/lib/mysql:rw

volumes:
  mysql-data:
  data:
