version: "3.6"

services:
  gateway:
    build: ../cloud/apigateway
    ports:
      - "8080:8080"
    depends_on:
      - user
      - product
      - order

  user:
    build: ../microservice/user-service
    ports:
      - "8082:8082"
    depends_on:
      - db

  product:
    build: ../microservice/product-service
    ports:
      - "8083:8083"
    depends_on:
      - db

  order:
    build: ../microservice/order-service
    ports:
      - "8081:8081"
    depends_on:
      - db


  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/casa/volumes-db/mysql-data:/var/lib/mysql:rw



volumes:
  mysql-data:
  data:
