spring:
  application:
    name: product-service

  config:
    import: "optional:configserver:http://localhost:8088"

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user123
